name: Auto Release

on:
  push:
    branches: [ main, master ]
    paths:
      - 'abstracts-index/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download CLI tool
        run: |
          mkdir -p $RUNNER_TEMP/bin
          cd $RUNNER_TEMP/bin

          wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.6/dify-plugin-linux-amd64
          chmod +x dify-plugin-linux-amd64

          echo "CLI tool location:"
          pwd
          ls -la dify-plugin-linux-amd64

      - name: Get basic info from manifest
        id: get_basic_info
        run: |
          PLUGIN_NAME=$(grep "^name:" manifest.yaml | cut -d' ' -f2)
          echo "Plugin name: $PLUGIN_NAME"
          echo "plugin_name=$PLUGIN_NAME" >> $GITHUB_OUTPUT

          VERSION=$(grep "^version:" manifest.yaml | cut -d' ' -f2)
          echo "Plugin version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

          AUTHOR=$(grep "^author:" manifest.yaml | cut -d' ' -f2)
          echo "Plugin author: $AUTHOR"
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT

      - name: Package Plugin
        id: package
        run: |
          cd $GITHUB_WORKSPACE
          PACKAGE_NAME="${{ steps.get_basic_info.outputs.plugin_name }}-${{ steps.get_basic_info.outputs.version }}.difypkg"
          $RUNNER_TEMP/bin/dify-plugin-linux-amd64 plugin package . -o "$PACKAGE_NAME"

          echo "Package result:"
          ls -la "$PACKAGE_NAME"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Delete existing release if exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.get_basic_info.outputs.tag }}"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG exists, deleting..."
            gh release delete "$TAG" --yes
            git push --delete origin "$TAG" || true
          fi

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.get_basic_info.outputs.tag }}"
          VERSION="${{ steps.get_basic_info.outputs.version }}"
          PACKAGE_NAME="${{ steps.package.outputs.package_name }}"
          
          # Create release notes
          cat > release_notes.md << EOF
          ## Abstracts Index Dify Plugin v${VERSION}
          
          ### Features
          - Semantic search across 110 million academic publications
          - Powered by abstracts-search with OpenAlex dataset
          - Uses stella_en_1.5B_v5 model for embeddings
          - FAISS indexing for fast similarity search
          - Dual format output (text and JSON)
          - No API keys required
          
          ### Installation
          Download the \`${PACKAGE_NAME}\` file and upload it to your Dify platform.
          
          For detailed instructions, please refer to the [README](https://github.com/${{ github.repository }}/blob/main/abstracts-index/README.md).
          EOF
          
          # Create release
          gh release create "$TAG" \
            --title "Abstracts Index Plugin v${VERSION}" \
            --notes-file release_notes.md \
            "./${PACKAGE_NAME}"